# This is a basic workflow to help you get started with Actions

name: JMeter Load Test Plan

# Controls when the workflow will run
on:
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
  
env:
  OKTA_CREDENTIALS_V2: ${{ secrets.OKTA_CREDENTIALS_V2 }}
                            

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  
     # Fetch the okta credential and Parse JSON and store in the variable
      - name: fetch the json value
        id: oktaCredentialV2  
        run:  |
           echo "::set-output name=CLIENT_ID::$(echo "$OKTA_CREDENTIALS_V2" | jq -r '.clientId')"
           echo "::set-output name=CLIENT_SECRET::$(echo "$OKTA_CREDENTIALS_V2" | jq -r '.clientSecret')"
           echo "::set-output name=OKTA_USER::$(echo "$OKTA_CREDENTIALS_V2" | jq -r '.users.dmsAdminUser.username')"
           echo "::set-output name=OKTA_PWD::$(echo "$OKTA_CREDENTIALS_V2" | jq -r '.users.dmsAdminUser.password')"
      - run: |
          echo ${{steps.oktaCredentialV2.outputs.CLIENT_ID}}
          echo ${{steps.oktaCredentialV2.outputs.CLIENT_SECRET}}
          echo ${{steps.oktaCredentialV2.outputs.OKTA_USER}} 
          echo ${{steps.oktaCredentialV2.outputs.OKTA_PWD}}


   
          
